include:
  - ./infrastructure/compose.data.yaml
  - ./infrastructure/compose.monitoring.yaml

services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    command:
      - --spring.profiles.active=${SPRING_PROFILE:-database}
      - --server.port=${SPRING_PORT:-8083}
    networks:
      - load-balancer
      - backend
    scale: ${SPRING_REPLICAS:-1}
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 20s

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8080:8080"
    volumes:
      - ./infrastructure/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - load-balancer

networks:
  load-balancer: { }
  backend: { }