include:
  - ./infrastructure/compose.data.yaml
  - ./infrastructure/compose.monitoring.yaml

services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: app
    command: --spring.profiles.active=database
    ports:
      - '8080:8080'
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 20s