include:
  - ./infrastructure/compose.data.yaml
  - ./infrastructure/compose.monitoring.yaml

services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: app
    command: --spring.profiles.active=cache
    ports:
      - '8080:8080'
    networks:
      - default-network

  postgres:
    image: 'postgres:latest'
    container_name: db
    environment:
      - 'POSTGRES_PASSWORD=user'
      - 'POSTGRES_USER=user'
      - 'POSTGRES_DB=postgres'
    ports:
      - '5432:5432'
    networks:
      - default-network
    volumes:
      - ./postgres-data:/var/lib/postgresql/data


  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - default-network

networks:
    default-network: {}
