global:
  scrape_interval: 2s
  scrape_timeout: 1s
  evaluation_interval: 15s

scrape_configs:
  - job_name: prometheus
    honor_timestamps: true
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets:
          - localhost:9090

  - job_name: 'spring actuator'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'app:8080' ]
        labels:
          alias: 'app'

  - job_name: postgres
    static_configs:
      - targets: [ "postgres-exporter:9187" ]

  - job_name: redis_exporter
    static_configs:
      - targets: [ 'redis-exporter:9121' ]

  - job_name: dex
    scrape_interval: 3s
    scrape_timeout: 3s
    static_configs:
      - targets: [ 'dex:3456' ]