services:
  k6:
    image: grafana/k6
    container_name: k6
    restart: unless-stopped
    environment:
      - K6_PROMETHEUS_RW_SERVER_URL=http://my-prometheus:9090/api/v1/write
      - K6_PROMETHEUS_RW_TREND_AS_NATIVE_HISTOGRAM=true
      - K6_PROMETHEUS_RW_PUSH_INTERVAL=2s
    command:
      - run
      - /etc/k6/benchmark-script.js
      - --address
      - 0.0.0.0:6565
      - --out
      - experimental-prometheus-rw
    ports: 
      - '6565:6565'
    volumes:
      - ./k6/:/etc/k6/

  grafana:
    image: grafana/grafana
    container_name: my-grafana
    restart: unless-stopped
    ports:
      - '3000:3000'
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./grafana:/etc/grafana/

  prometheus:
    image: prom/prometheus
    container_name: my-prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yaml
      - --web.enable-remote-write-receiver
      - --enable-feature=native-histograms
    ports:
      - '9090:9090'
    restart: unless-stopped
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus-storage:/prometheus

  postgres-exporter:
    image: quay.io/prometheuscommunity/postgres-exporter
    ports:
      - '9187:9187'
    container_name: postgres-exporter
    environment:
      - DATA_SOURCE_URI=db:5432/postgres?sslmode=disable
      - DATA_SOURCE_USER=user
      - DATA_SOURCE_PASS=user
    restart: unless-stopped

  redis-exporter:
    image: oliver006/redis_exporter
    ports:
      - '9121:9121'
    container_name: redis-exporter
    environment:
      - REDIS_ADDR=redis:6379
    restart: unless-stopped

  dex:
    image: spx01/dex
    container_name: dex
    environment:
      DEX_PORT: 3456
    volumes:
      - /run/user/1000/docker.sock:/var/run/docker.sock
    ports:
      - '3456:3456'
    restart: always
volumes:
  grafana-storage: {}
  prometheus-storage: {}
